### ISSUE TITLE
no duplicar logica de movimientos

### ISSUE THREAD

**Issue by lspigariol** [pdep-utn-frd/2019-tpwgame-comanches#4]
el control de los movimientos y los margenes se repite.
si definieron objetos para manejar las direcciones y movimientos, deleguen alli esa responsabilidad y eviten volver a hacerla en otro lado.

**Comment by juanbono** [comment]
Puntualmente la duplicacion es en las lineas https://github.com/pdep-utn-frd/2019-tpwgame-comanches/blob/d5cdfbcde90056a177d2bd3750b5cfcaa69f7ccf/src/direcciones.wlk#L10  y despues en la linea https://github.com/pdep-utn-frd/2019-tpwgame-comanches/blob/d5cdfbcde90056a177d2bd3750b5cfcaa69f7ccf/src/elementos.wlk#L50 se realiza el chequeo de nuevo. El chequeo debe ser realizado en un lugar o en otro. Preferentemente en los objetos que heredan de `Direccion`

**Comment by GINOXCVIII** [comment]
corregido

**Comment by juanbono** [comment]
Corrigido
