### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by lspigariol** [pdep-utn-frd/2019-tpwgame-comanches#5]
el readme conviene que tenga extension .md 
el formato es facil de usar

ponganle alguna descripcion, autores, captura de pantalla o algo así.

**Comment by GINOXCVIII** [comment]
ok

**Comment by juanbono** [comment]
El issue fue solucionado correctamente, dejo un link a un recurso que explica el formato [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
